################################################################################
# Substitution Variables
################################################################################
substitutions:
  name: home
  friendly_name: Home
  modbus_controller_addr: "1"
  modbus_switch1_address: "10"
  sampling_time: 30s

################################################################################
# Board Configuration
################################################################################
esphome:
  name: $name
  friendly_name: $friendly_name

esp32:
  board: esp32dev
  framework:
    type: arduino

################################################################################
# Enable logging
################################################################################
logger:
  baud_rate: 0

################################################################################
# Enable Home Assistant API
################################################################################
api:
  encryption:
    key: !secret api_encryption_key

################################################################################
# OTA
################################################################################
ota:
  - platform: esphome
    password: !secret ota_password

################################################################################
# Ethernet
################################################################################
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0

################################################################################
# Web Server
################################################################################
web_server:
  port: 80
  version: 2
  include_internal: true
  auth:
    username: !secret web_server_user
    password: !secret web_server_password
  local: true

################################################################################
# Status led
################################################################################
status_led:
  pin:
    number: GPIO2
    inverted: false

################################################################################
# Time
################################################################################
time:
  - platform: homeassistant

################################################################################
# I2C
################################################################################
i2c:
  sda: 5
  scl: 4
  scan: true
  id: bus_a

pcf8574:
  - id: "pcf8574_hub_out_1" # for output channel 1-8
    address: 0x24
  - id: "pcf8574_hub_in_1" # for input channel 1-8
    address: 0x22

################################################################################
# Modbus
################################################################################
# TODO: in official documentation there is wrong values. I had to clone it locally and adjust
# external_components:
#   - source:
#       type: git
#       url: https://github.com/hzkincony/esphome-kc868-ha
#       ref: v3.0.1
external_components:
  - source:
      type: local
      path: components

uart:
  - id: myuart1
    tx_pin: 13
    rx_pin: 15
    baud_rate: 9600

kc868_ha:

################################################################################
# Sensors
################################################################################
sensor:
  #-------------------------------------------------------------------------------
  # ESP Generic Sensors
  #-------------------------------------------------------------------------------
  - platform: uptime
    id: ${name}_uptime
    update_interval: $sampling_time
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: ${name}_uptime_human
            state: !lambda |-
              int seconds = round(id(${name}_uptime).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();

################################################################################
# Text Sensors
################################################################################
text_sensor:
  #-------------------------------------------------------------------------------
  # ESP32 internal sensors
  #-------------------------------------------------------------------------------
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true

  #-------------------------------------------------------------------------------
  # Custom Text sensors
  #-------------------------------------------------------------------------------
  - platform: template
    name: Uptime
    id: ${name}_uptime_human
    icon: mdi:clock-start

################################################################################
# Switches
################################################################################
switch:
  #-------------------------------------------------------------------------------
  # ESP32 internal
  #-------------------------------------------------------------------------------
  - platform: restart
    name: "Restart"

  #-------------------------------------------------------------------------------
  # GPIO outputs
  #-------------------------------------------------------------------------------
  - platform: gpio
    id: light1
    name: "Light 1"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 0
      mode: OUTPUT
      inverted: true
    on_turn_on:
      then:
        - switch.turn_on: switch1_led1
    on_turn_off:
      then:
        - switch.turn_off: switch1_led1

  - platform: gpio
    id: light2
    name: "Light 2"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 1
      mode: OUTPUT
      inverted: true
    on_turn_on:
      then:
        - switch.turn_on: switch1_led2
    on_turn_off:
      then:
        - switch.turn_off: switch1_led2

  - platform: gpio
    id: light3
    name: "Light 3"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 2
      mode: OUTPUT
      inverted: true
    on_turn_on:
      then:
        - switch.turn_on: switch1_led3
    on_turn_off:
      then:
        - switch.turn_off: switch1_led3

  - platform: gpio
    id: light4
    name: "Light 4"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 3
      mode: OUTPUT
      inverted: true
    on_turn_on:
      then:
        - switch.turn_on: switch1_led4
    on_turn_off:
      then:
        - switch.turn_off: switch1_led4

  - platform: gpio
    id: light5
    name: "Light 5"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 4
      mode: OUTPUT
      inverted: true
    on_turn_on:
      then:
        - switch.turn_on: switch1_led5
    on_turn_off:
      then:
        - switch.turn_off: switch1_led5

  - platform: gpio
    id: light6
    name: "Light 6"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 5
      mode: OUTPUT
      inverted: true
    on_turn_on:
      then:
        - switch.turn_on: switch1_led6
    on_turn_off:
      then:
        - switch.turn_off: switch1_led6

  - platform: gpio
    id: light7
    name: "Light 7"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 6
      mode: OUTPUT
      inverted: true

  - platform: gpio
    id: light8
    name: "Light 8"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 7
      mode: OUTPUT
      inverted: true

  #-------------------------------------------------------------------------------
  # Modbus outputs
  #-------------------------------------------------------------------------------
  - platform: kc868_ha
    target_relay_controller_addr: $modbus_controller_addr
    switch_adapter_addr: $modbus_switch1_address
    bind_output: 1
    id: switch1_led1

  - platform: kc868_ha
    target_relay_controller_addr: $modbus_controller_addr
    switch_adapter_addr: $modbus_switch1_address
    bind_output: 2
    id: switch1_led2

  - platform: kc868_ha
    target_relay_controller_addr: $modbus_controller_addr
    switch_adapter_addr: $modbus_switch1_address
    bind_output: 3
    id: switch1_led3

  - platform: kc868_ha
    target_relay_controller_addr: $modbus_controller_addr
    switch_adapter_addr: $modbus_switch1_address
    bind_output: 4
    id: switch1_led4

  - platform: kc868_ha
    target_relay_controller_addr: $modbus_controller_addr
    switch_adapter_addr: $modbus_switch1_address
    bind_output: 5
    id: switch1_led5

  - platform: kc868_ha
    target_relay_controller_addr: $modbus_controller_addr
    switch_adapter_addr: $modbus_switch1_address
    bind_output: 6
    id: switch1_led6

################################################################################
# Binary sensors
################################################################################
binary_sensor:
  #-------------------------------------------------------------------------------
  # GPIO inputs
  #-------------------------------------------------------------------------------
  - platform: gpio
    id: input1
    on_press:
      then:
        - switch.toggle: light1
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 0
      mode: INPUT
      inverted: true

  - platform: gpio
    id: "input2"
    on_press:
      then:
        - switch.toggle: light2
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 1
      mode: INPUT
      inverted: true

  - platform: gpio
    id: "input3"
    on_press:
      then:
        - switch.toggle: light3
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 2
      mode: INPUT
      inverted: true

  - platform: gpio
    id: "input4"
    on_press:
      then:
        - switch.toggle: light4
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 3
      mode: INPUT
      inverted: true

  - platform: gpio
    id: "input5"
    on_press:
      then:
        - switch.toggle: light5
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 4
      mode: INPUT
      inverted: true

  - platform: gpio
    id: "input6"
    on_press:
      then:
        - switch.toggle: light6
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 5
      mode: INPUT
      inverted: true

  - platform: gpio
    id: "input7"
    on_press:
      then:
        - switch.toggle: light7
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 6
      mode: INPUT
      inverted: true

  - platform: gpio
    id: "input8"
    on_press:
      then:
        - switch.toggle: light8
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 7
      mode: INPUT
      inverted: true

  #-------------------------------------------------------------------------------
  # Modbus inputs
  #-------------------------------------------------------------------------------
  - platform: kc868_ha
    target_relay_controller_addr: $modbus_controller_addr
    switch_adapter_addr: $modbus_switch1_address
    bind_output: 1
    id: "switch1_button1"
    on_press:
      then:
        - switch.toggle: light1

  - platform: kc868_ha
    target_relay_controller_addr: $modbus_controller_addr
    switch_adapter_addr: $modbus_switch1_address
    bind_output: 2
    id: "switch1_button2"
    on_press:
      then:
        - switch.toggle: light2

  - platform: kc868_ha
    target_relay_controller_addr: $modbus_controller_addr
    switch_adapter_addr: $modbus_switch1_address
    bind_output: 3
    id: "switch1_button3"
    on_press:
      then:
        - switch.toggle: light3

  - platform: kc868_ha
    target_relay_controller_addr: $modbus_controller_addr
    switch_adapter_addr: $modbus_switch1_address
    bind_output: 4
    id: "switch1_button4"
    on_press:
      then:
        - switch.toggle: light4

  - platform: kc868_ha
    target_relay_controller_addr: $modbus_controller_addr
    switch_adapter_addr: $modbus_switch1_address
    bind_output: 5
    id: "switch1_button5"
    on_press:
      then:
        - switch.toggle: light5

  - platform: kc868_ha
    target_relay_controller_addr: $modbus_controller_addr
    switch_adapter_addr: $modbus_switch1_address
    bind_output: 6
    id: "switch1_button6"
    on_press:
      then:
        - switch.toggle: light6
