- platform: history_stats
  type: time
  name: Kvetoslavov occupied
  entity_id: binary_sensor.someone_in_kvetoslavov
  state: "on"
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"